openapi: 3.0.1
info:
  title: AgriProductTrackingAPI
  description: API Definition of AgriProductTrackingAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/agriProduct
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    put:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
    delete:
      responses:
        default:
          description: Default response
    patch:
      responses:
        default:
          description: Default response
